{
  "status" : 0,
  "message" : "success",
  "content" : [
    {
      "usersBuyRecordVO" : {
        "ifShowButton" : null,
        "isMember" : true,
        "memberStatusText" : "你的会员已于 2022-11-11到期",
        "historyBuy" : true,
        "ifBuySvip" : true,
        "buttonText" : "立即续费"
      },
      "itemList" : [
        {
          "discountDesc" : "疫情限期特惠",
          "itemDesc" : "口语答案、写作范文、会员课程、独家题库等你来解锁",
          "skuName" : "120天",
          "itemCount" : 120,
          "picture" : "",
          "itemName" : "雅思哥会员",
          "deliveryFlag" : false,
          "ifRecommendItem" : true,
          "tag" : "超值推荐",
          "price" : 0.99,
          "iosLink" : "com.yasBro.v2.vip120.0.99rmb",
          "itemCode" : "VVIP20210901191055808811",
          "originalPrice" : 0.99,
          "payType" : "1_2_3",
          "orderInfo" : "0",
          "sort" : 1,
          "itemId" : "20220602184856743691"
        },
        {
          "discountDesc" : "立省150元",
          "itemDesc" : "口语答案、写作范文、会员课程、独家题库等你来解锁",
          "skuName" : "30天",
          "itemCount" : 30,
          "picture" : "",
          "itemName" : "雅思哥会员",
          "deliveryFlag" : false,
          "ifRecommendItem" : false,
          "tag" : "",
          "price" : 238,
          "iosLink" : "com.yasBro.v2.vip30.238rmb",
          "itemCode" : "VVIP20210901191055808811",
          "originalPrice" : 238,
          "payType" : "1_2_3",
          "orderInfo" : "0",
          "sort" : 2,
          "itemId" : "20210901191055813527"
        },
        {
          "discountDesc" : "立省50元",
          "itemDesc" : "口语答案、写作范文、会员课程、独家题库等你来解锁",
          "skuName" : "14天",
          "itemCount" : 14,
          "picture" : "",
          "itemName" : "雅思哥会员",
          "deliveryFlag" : false,
          "ifRecommendItem" : false,
          "tag" : "短期冲刺必备",
          "price" : 188,
          "iosLink" : "com.yasBro.v2.vip14.188rmb",
          "itemCode" : "VVIP20210901191055808811",
          "originalPrice" : 188,
          "payType" : "1_2_3",
          "orderInfo" : "0",
          "sort" : 3,
          "itemId" : "20210901191055808840"
        },
        {
          "discountDesc" : "立省180元",
          "itemDesc" : "口语答案、写作范文、会员课程、独家题库等你来解锁",
          "skuName" : "60天",
          "itemCount" : 60,
          "picture" : "",
          "itemName" : "雅思哥会员",
          "deliveryFlag" : false,
          "ifRecommendItem" : false,
          "tag" : "",
          "price" : 418,
          "iosLink" : "com.yasBro.v2.vip60.418rmb",
          "itemCode" : "VVIP20210901191055808811",
          "originalPrice" : 418,
          "payType" : "1_2_3",
          "orderInfo" : "0",
          "sort" : 4,
          "itemId" : "20210901191055817168"
        },
        {
          "discountDesc" : "立省200元",
          "itemDesc" : "口语答案、写作范文、会员课程、独家题库等你来解锁",
          "skuName" : "90天",
          "itemCount" : 90,
          "picture" : "",
          "itemName" : "雅思哥会员",
          "deliveryFlag" : false,
          "ifRecommendItem" : false,
          "tag" : "",
          "price" : 518,
          "iosLink" : "com.yasBro.v2.vip90.518rmb",
          "itemCode" : "VVIP20210901191055808811",
          "originalPrice" : 518,
          "payType" : "1_2_3",
          "orderInfo" : "0",
          "sort" : 5,
          "itemId" : "20211018095154855254"
        }
      ],
      "couponItemList" : [
        {
          "discountDesc" : null,
          "itemDesc" : null,
          "skuName" : "60天",
          "itemCount" : 60,
          "picture" : "",
          "itemName" : "雅思哥会员",
          "deliveryFlag" : false,
          "ifRecommendItem" : false,
          "tag" : null,
          "price" : 388,
          "iosLink" : "com.yasBro.v2.vip60.388rmb",
          "itemCode" : "VVIP20210901190559836602",
          "originalPrice" : 588,
          "payType" : "1_2_3",
          "orderInfo" : "",
          "sort" : 1,
          "itemId" : "20210901190559846999"
        },
        {
          "discountDesc" : null,
          "itemDesc" : null,
          "skuName" : "30天",
          "itemCount" : 30,
          "picture" : "",
          "itemName" : "雅思哥会员",
          "deliveryFlag" : false,
          "ifRecommendItem" : false,
          "tag" : null,
          "price" : 218,
          "iosLink" : "com.yasBro.v2.vip30.218rmb",
          "itemCode" : "VVIP20210901190559836602",
          "originalPrice" : 388,
          "payType" : "1_2_3",
          "orderInfo" : "",
          "sort" : 2,
          "itemId" : "20210901190559842170"
        },
        {
          "discountDesc" : null,
          "itemDesc" : null,
          "skuName" : "14天",
          "itemCount" : 14,
          "picture" : "",
          "itemName" : "雅思哥会员",
          "deliveryFlag" : false,
          "ifRecommendItem" : false,
          "tag" : null,
          "price" : 178,
          "iosLink" : "com.yasBro.v2.vip14.178rmb",
          "itemCode" : "VVIP20210901190559836602",
          "originalPrice" : 238,
          "payType" : "1_2_3",
          "orderInfo" : "",
          "sort" : 3,
          "itemId" : "20210901190559837327"
        }
      ]
    }
  ],
  "showMessage" : null
}